services:
  telegram-bot:
    build: .
    container_name: telegram-ai-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SESSION_PATH=/app/sessions/mi_sesion
    volumes:
      # Volumen para mantener la sesión de Telegram activa
      - telegram_session:/app/sessions
      # Volumen para historial (lectura/escritura)
      - ./historial.json:/app/historial.json
    networks:
      - bot-network

volumes:
  telegram_session:
    driver: local

networks:
  bot-network:
    driver: bridge
