version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-ai-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - CHAT_ID=${CHAT_ID}
    volumes:
      # Volumen para mantener la sesión de Telegram activa
      - telegram_session:/app/sessions
      # Volumen para historial si lo necesitas persistente
      - ./historial.json:/app/historial.json:ro
    networks:
      - bot-network

volumes:
  telegram_session:
    driver: local

networks:
  bot-network:
    driver: bridge
